Add image for question
e-spres-oh/qwizard pull request #11
Opened 2021-03-02 20:33 UTC by horiaradu

* DragAndDrop file input
* handle image / image url state
* call API

2021-03-02 20:34 UTC, horiaradu commented
I didn't find how to:

* edit the photo of a question (edit the question actually)
* choose / edit a quiz's photo

2021-03-03 08:16 UTC, PaulMacinic commented on src/components/DragAndDrop.module.css
> +  max-width: 100%;
Image looks a bit weird, change `.image` to:
.image {
    position: absolute;
    height: auto;
    width: 100%;
    max-height: 100%;
    top: 0;
    left: 0;
 }

2021-03-03 08:24 UTC, PaulMacinic commented on src/screens/CreateQuiz.js
> +                        activeQuestion
We need to handle here the cases where a quiz has no image. It's not mandatory for a quiz to have an image, In that case we should not show any image here.

2021-03-03 08:28 UTC, PaulMacinic requested changes
See comments

2021-03-03 08:32 UTC, horiaradu commented on src/screens/CreateQuiz.js
> +                        activeQuestion
at this point, if it has no image, i will show the empty drag and drop area

2021-03-03 08:35 UTC, horiaradu commented on src/components/DragAndDrop.module.css
> +  max-width: 100%;
this breaks the aspect ratio of the image

2021-03-03 08:59 UTC, merged